# https://docs.docker.com/compose/gettingstarted/
# https://stackoverflow.com/questions/53507378/create-docker-file-for-client-and-server
# https://docs.docker.com/compose/file-watch/
# https://stackoverflow.com/questions/78500319/how-to-pull-model-automatically-with-container-creation

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./server/scripts/entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]
    container_name: ollama
  server:
    build: ./server
    container_name: server
    develop:
      watch:
        - action: sync
          path: ./server
          target: ./server
          ignore:
            - ./server/node_modules/
        - action: rebuild
          path: ./server/package.json
    ports:
      - 80:80
  client:
    build: ./client
    container_name: client
    develop:
      watch:
        - action: sync
          path: ./client
          target: ./client
          ignore:
            - ./client/node_modules/
        - action: rebuild
          path: ./client/package.json
    ports:
      - 3000:3000